const $=id=>document.getElementById(id);let current=null;let videos=JSON.parse(localStorage.getItem('tikview-feed')||'[]');
function error(m){$('error').textContent=m;$('error').classList.remove('hidden')}function hideError(){$('error').classList.add('hidden')}
async function resolve(url){const r=await fetch('/api/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to resolve link.');return d}
async function load(){hideError();const u=$('url').value.trim();if(!u)return error('Paste a TikTok link first.');$('watch').disabled=true;$('watch').textContent='Loading...';try{const d=await resolve(u);current={id:d.videoId,url:d.url};showPlayer()}catch(e){error(e.message)}finally{$('watch').disabled=false;$('watch').textContent='Watch video'}}
function playerUrl(id){return `https://www.tiktok.com/player/v1/${id}?controls=1&progress_bar=1&play_button=1&volume_control=1&fullscreen_button=1&timestamp=1&description=0&music_info=0&loop=0&autoplay=0&rel=0`}
function showPlayer(){$('home').classList.add('hidden');$('feedView').classList.add('hidden');$('playerView').classList.remove('hidden');$('player').src=playerUrl(current.id)}
function home(){$('player').src='';$('playerView').classList.add('hidden');$('feedView').classList.add('hidden');$('home').classList.remove('hidden')}
function save(){localStorage.setItem('tikview-feed',JSON.stringify(videos))}
function add(){if(!current)return;if(!videos.some(v=>v.id===current.id)){videos.push(current);save()}}
function buildFeed(){const f=$('feed');f.innerHTML='';videos.forEach(v=>{const item=document.createElement('div');item.className='feedItem';const i=document.createElement('iframe');i.allow='autoplay;encrypted-media;fullscreen';i.allowFullscreen=true;i.src=playerUrl(v.id);item.appendChild(i);f.appendChild(item)});$('counter').textContent=`1 / ${videos.length}`;const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const n=[...f.children].indexOf(e.target);$('counter').textContent=`${n+1} / ${videos.length}`}}),{threshold:.65});[...f.children].forEach(x=>obs.observe(x))}
function doom(){if(!videos.length){if(current){videos.push(current);save()}else return error('Add a video first, then use Doomscroll.')}buildFeed();$('home').classList.add('hidden');$('playerView').classList.add('hidden');$('feedView').classList.remove('hidden');document.body.style.overflow='hidden'}
function stopDoom(){ $('feedView').classList.add('hidden');document.body.style.overflow='';$('home').classList.remove('hidden')}
$('watch').onclick=load;$('url').onkeydown=e=>{if(e.key==='Enter')load()};$('paste').onclick=async()=>{try{$('url').value=(await navigator.clipboard.readText()).trim();if($('url').value)load()}catch{error('Clipboard access was blocked. Paste the link manually.')}};$('back').onclick=home;$('add').onclick=add;$('doom').onclick=doom;$('feedBtn').onclick=doom;$('feedBack').onclick=stopDoom;$('copy').onclick=async()=>{if(current)try{await navigator.clipboard.writeText(current.url);$('copy').textContent='Copied!';setTimeout(()=>$('copy').textContent='Copy link',1200)}catch{error('Unable to copy link.')}};$('full').onclick=()=>{const f=document.querySelector('.frame');document.fullscreenElement?document.exitFullscreen():f.requestFullscreen?.()};
